version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy


  consumerqueue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    depends_on:
      db:
        condition: service_healthy


  db:
    platform: linux/x86_64
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 15
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
