"""empty message

Revision ID: e63b3b2574d0
Revises: 3caeb1ba10b9
Create Date: 2022-03-06 21:34:05.258937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63b3b2574d0'
down_revision = '3caeb1ba10b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('myindex', 'product_user', ['user_id', 'product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('myindex', table_name='product_user')
    # ### end Alembic commands ###
